In [3]:
import numpy as np 

np.array([1,2,3,4])


array([1, 2, 3, 4])

In [4]:
from numpy import array

array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [12]:
from numpy import array

user = ["khush","atul","khushi","berlin"]

new_user = user +["tokyo","rio"]

print(len(new_user))

np_arr = np.array(new_user)
print(np_arr)



6
['khush' 'atul' 'khushi' 'berlin' 'tokyo' 'rio']


In [16]:
import numpy as np 

height=[1.73,1.76,1.88,1.55]
np_height = np.array([height])

weight =[65.4,64.2,63.5,67.2]
np_weight = np.array([weight])

bmi = np_height / np_weight ** 2
# print(bim)
bmi

array([[0.00040447, 0.00042701, 0.00046624, 0.00034324]])

In [18]:
import numpy as np 

x= ["k",True,1,0.5]

np_x = np.array(x)
type(np_x)
print(np_x.dtype)

<U32


In [ ]:
# 2D Array in NumPy  ......

import numpy as np 

arr = np.array([1,2,3])

print(arr.shape)



# 2D Array normal ....
arr =[[1,2,3,] ,[4,5,6,7]
]
print(arr)


arr_2 = np.array(arr)
print(arr_2.shape)

(3,)
[[1, 2, 3], [4, 5, 6, 7]]


AttributeError: 'list' object has no attribute 'shape'