In [3]:
import numpy as np 

np.array([1,2,3,4])


array([1, 2, 3, 4])

In [4]:
from numpy import array

array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [12]:
from numpy import array

user = ["khush","atul","khushi","berlin"]

new_user = user +["tokyo","rio"]

print(len(new_user))

np_arr = np.array(new_user)
print(np_arr)



6
['khush' 'atul' 'khushi' 'berlin' 'tokyo' 'rio']


In [16]:
import numpy as np 

height=[1.73,1.76,1.88,1.55]
np_height = np.array([height])

weight =[65.4,64.2,63.5,67.2]
np_weight = np.array([weight])

bmi = np_height / np_weight ** 2
# print(bim)
bmi

array([[0.00040447, 0.00042701, 0.00046624, 0.00034324]])

In [18]:
import numpy as np 

x= ["k",True,1,0.5]

np_x = np.array(x)
type(np_x)
print(np_x.dtype)

<U32


In [32]:
# 2D Array in NumPy  ......

import numpy as np 

arr = np.array([1,2,3])

print(arr.shape)


# 2D Array normal ....
arr_2=[[1,2,3,8] ,[4,5,6,7]
]
# print(arr)

# shape array 
arr_3 = np.array(arr_2)
print(arr_3.shape)

(3,)
(2, 4)


In [ ]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120]
])

print(arr.shape)
print(arr[0,1])  #print only row 1st 2nd coloumn element 20 
print(arr[2,2])  # print only 90 
print(arr[0,:])  # print 1st row nd 1st coloumn all element 
print(arr[3,:])  # print 3rd row all coloum 
print(arr[0:,0]) # print 1st rowm or all coloums 

(4, 3)
20
90
[10 20 30]
[100 110 120]
[ 10  40  70 100]
